# Default target
run:
	python write_grids.py

# Clean target (optional, to clean up .pyc or __pycache__)
clean:
	rm -rf __pycache__ *.pyc
	rm -rf ./40006000/*
	rm -rf ./40006001/*
	rm -rf ./40006002/*
